name: publish

on:
  workflow_dispatch:
    inputs:
      kind:
        description: Kind of release
        default: minor
        type: choice
        options:
        - prepatch
        - patch
        - preminor
        - minor
        - premajor
        - major
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Publish update
        uses: boywithkeyboard/publisher@v3
        with:
          kind: ${{github.event.inputs.kind}}
